routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>['web']],function (){
    Route::get('/', function () {
        return view('welcome')  ;
    });
    Route::resource('home','UserController');
    Route::get('deshboard','UserController@login');
    Route::post('deshboard','UserController@login');
    Route::get('/logout','UserController@logout');
    Route::resource('author','AuthorController');
    Route::post('active/{author}','AuthorController@active');
    Route::resource('book','BookController');
    Route::get('bactive/{book}','BookController@bactive');


});

resources/views/addauthor.blade.php
@extends('layouts.master')
@section('js')
    <script type="text/javascript" src="{{ asset('asset/js/addauthor.js') }}" defer></script>
    <style>
        .error{
            color: red;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center card-title">Author</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <form method="post" action="{{route('author.store')}}" id="form">
                    @csrf
                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter Name" aria-describedby="helpId">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Date Of Birth</label>
                        <input type="date" name="date" id="date" class="form-control @error('date') is-invalid @enderror" placeholder="Enter date" aria-describedby="helpId">
                        @error('date')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Gender</label>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender"value="male" checked>
                            <label class="form-check-label" for="materialUnchecked">Male</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender" value="female">
                            <label class="form-check-label" for="materialUnchecked">Female</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender" value="other">
                            <label class="form-check-label" for="materialChecked">Other</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Address</label>
                        <textarea class="form-control @error('address') is-invalid @enderror" name="address" id="address" rows="3" id="comment"></textarea>
                        <small class="error"></small>
                        @error('address')
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Mobile No</label>
                        <input type="text" name="mobileno" id="mobile" class="form-control @error('mobileno') is-invalid @enderror" placeholder="Enter Mobile No" aria-describedby="helpId">
                        <small class="error"></small>
                        @error('mobileno')
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description" rows="3" id="comment"></textarea>
                        <small class="error"></small>
                        @error('description')
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="submit" name="insert" id="btn" class="btn btn-success" value="Submit" aria-describedby="helpId">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/addbook.blade.php
@extends('layouts.master')
@section('js')
    <script type="text/javascript" src="{{ asset('asset/js/addbook.js') }}" defer></script>
    <style>
        label.error{
            color: red;
        }
    </style>
    @endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center card-title">Book</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <form method="post" action="{{route('book.store')}}" id="form" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="">Title</label>
                        <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" placeholder="Enter Title" aria-describedby="helpId">
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Pages</label>
                        <input type="number" name="pages" id="page" class="form-control @error('pages') is-invalid @enderror" placeholder="Enter Book Page" aria-describedby="helpId">
                        @error('pages')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Language</label>
                        <input type="text" name="language" id="language" class="form-control @error('language') is-invalid @enderror" placeholder="Enter Book Language" aria-describedby="helpId">
                        @error('language')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Book Author</label>
                        <select class="custom-select @error('book_author') is-invalid @enderror" name="book_author" id="book_author">
                            <option hidden value="">Book Author</option>
                            @foreach($author as $author)
                            <option value="{{ $author->id }}">{{ $author->name }}</option>
                            @endforeach
                        </select>
                        @error('book_author')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Cover image</label>
                        <input type="file" name="cover_image" id="cover_img" class="form-control @error('cover_image') is-invalid @enderror" placeholder="Enter Coverpage" aria-describedby="helpId">
                        @error('cover_image')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">ISBN NO</label>
                        <input type="text" name="isbn" id="isbn" class="form-control @error('isbn') is-invalid @enderror" placeholder="Enter ISBN NO" aria-describedby="helpId">
                        <small class="text-muted">Ex: [1-2222-3333-4]</small>
                        @error('isbn')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3"></textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="submit" name="insert" id="btn" class="btn btn-success" value="Submit" aria-describedby="helpId">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/author.blade.php
@extends('layouts.master')
@section('content')
    <div>
        <a class="btn btn-info" href="{{route('author.create')}}">Add Author</a>
    </div>
    <div>
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>NAME</th>
                <th>DOB</th>
                <th>GENDER</th>
                <th>ADDRESS</th>
                <th>MOBILE</th>
                <th>DESCRIPTION</th>
                <th>STATUS</th>
                <th>EDIT</th>
                <th>DELETE</th>
                <th>Active/Inactive</th>
            </tr>
            @foreach($author as $author)
                <tr>
                    <td>{{ $author->id }}</td>
                    <td>{{ $author->name }}</td>
                    <td>{{ $author->dob }}</td>
                    <td>{{ $author->gender }}</td>
                    <td>{{ $author->address }}</td>
                    <td>{{ $author->mobileno }}</td>
                    <td>{{ $author->description }}</td>
                    <td>{{ $author->status }}</td>
                    <td>
                        <form action="/author/{{$author->id}}/edit" method="post">
                            @csrf
                            @method('get')
                            <button type="submit" class="btn btn-success">Edit</button>
                        </form>
                    </td>
                    <td>
                        <form action="/author/{{$author->id}}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    <td>
                        <form action="/active/{{ $author->id }}" method="post">
                            @csrf
                            @if($author->status==1)
                                <button type="submit" class='btn btn-danger'>InActive</button>
                            @else
                                <button type="submit" class='btn btn-success'>Active</button>
                            @endif
                        </form>

                    </td>
                </tr>
            @endforeach

        </table>
    </div>
@endsection

resources/views/book.blade.php
@extends('layouts.master')
@section('content')
    <div>
        <a class="btn btn-info" href="{{route('book.create')}}">Add Book</a>
    </div>
    <div>
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>TITLE</th>
                <th>PAGES</th>
                <th>LANGUAGE</th>
                <th>AUTHOR NAME</th>
                <th>STATUS</th>
                <th>EDIT</th>
                <th>DELETE</th>
                <th>DETAIL</th>
                <th>Active/Inactive</th>
            </tr>
            @foreach($book as $book)
                <tr>
                    <td>{{ $book->id }}</td>
                    <td>{{ $book->title }}</td>
                    <td>{{ $book->pages }}</td>
                    <td>{{ $book->language }}</td>
                    <td>{{ $book->authors->name }}</td>
                    <td>{{ $book->status }}</td>
                    <td>
                        <form action="/book/{{$book->id}}/edit" method="post">
                            @csrf
                            @method('get')
                            <button type="submit" class="btn btn-success">Edit</button>
                        </form>
                    </td>
                    <td>
                        <form action="/book/{{$book->id}}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    <td>
                        <form action="/book/{{ $book->id }}" method="post">
                            @csrf
                            @method('get')
                            <button type="submit" class="btn btn-danger">DETAIL</button>
                        </form>
                    </td>
                    <td>
                        <form action="/bactive/{{ $book->id }}" method="get">
                            @csrf
                            @if($book->status==1)
                                <button type="submit" class='btn btn-danger'>InActive</button>
                            @else
                                <button type="submit" class='btn btn-success'>Active</button>
                            @endif
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

resources/views/deshboard.blade.php
@extends('layouts.master')
@section('content')
Welcome!!
@endsection

resources/views/editauthor.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center card-title">Author</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <form method="post" action="/author/{{$author->id}}" id="form">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ $author->name }}" aria-describedby="helpId">
                    </div>
                    <div class="form-group">
                        <label for="">Date Of Birth</label>
                        <input type="date" name="date" id="date" class="form-control" value="{{ $author->dob }}" aria-describedby="helpId">
                    </div>
                    <div class="form-group">
                        <label for="">Gender</label>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender" value="male" {{ $author->gender=='male'? 'checked':'' }}>
                            <label class="form-check-label" for="materialUnchecked">Male</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender" value="female" {{ $author->gender=='female'? 'checked':'' }}>
                            <label class="form-check-label" for="materialUnchecked">Female</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" class="form-check-input" id="gender" name="gender" value="other" {{ $author->gender=='other'? 'checked':'' }}>
                            <label class="form-check-label" for="materialChecked">Other</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Address</label>
                        <textarea class="form-control" name="address" id="address" rows="3" id="comment">{{ $author->address }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="">Mobile No</label>
                        <input type="text" name="mobileno" id="mobile" class="form-control" value="{{ $author->mobileno }}" aria-describedby="helpId">
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control" name="description" id="description" rows="3" id="comment">{{ $author->description }}</textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="insert" id="btn" class="btn btn-success" value="Submit" aria-describedby="helpId">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/editbook.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="text-center card-title">Book</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <form method="post" action="{{ route('book.update',[$book->id]) }}" id="form">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="">Title</label>
                        <input type="text" name="title" id="title" value="{{ $book->title }}" class="form-control @error('title') is-invalid @enderror" aria-describedby="helpId">
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Pages</label>
                        <input type="text" name="pages" id="page" value="{{ $book->pages }}" class="form-control @error('pages') is-invalid @enderror" aria-describedby="helpId">
                        @error('pages')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Language</label>
                        <input type="text" name="language" id="language" value="{{ $book->language }}" class="form-control @error('language') is-invalid @enderror" aria-describedby="helpId">
                        @error('language')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Book Author</label>
                        <select class="custom-select" name="book_author" id="book_author">
                            <option hidden>Book Author</option>
                            @foreach($author as $author)
                                <option value="{{ $author->id }}" {{ $book->book_author==$author->id?'selected':'' }}>{{ $author->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="">Cover image</label>
                        <input type="file" name="cover_image" class="@error('cover_image') is-invalid @enderror" value=""/>
                        @error('cover_image')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">ISBN NO</label>
                        <input type="text" name="isbn" id="isbn_no" value="{{ $book->isbn }}" class="form-control @error('isbn') is-invalid @enderror" aria-describedby="helpId">
                        <small class="text-muted">Ex: [1-2222-3333-4]</small>
                        @error('isbn')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3">{{ $book->description }}</textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="submit" name="insert" id="btn" class="btn btn-success" value="Submit" aria-describedby="helpId">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/show.blade.php
@extends('layouts.master')
@section('content')
    <div>
        <div class="card" style="width: 22rem;">
            <td><img class="card-img-top" src="{{asset('images/book_image/'.$book->cover_image)}}"></td>
            <div class="card-body">
                <h5 class="card-title"><b>Title : </b>{{ $book->title }}</h5>
                <h5 class="card-title"><b>Pages : </b>{{ $book->pages }}</h5>
                <h5 class="card-title"><b>Language : </b>{{ $book->language }}</h5>
                <h5 class="card-title"><b>Book Author : </b>{{ $book->authors->name }}</h5>
                <h5 class="card-title"><b>ISBN No. : </b>{{ $book->isbn }}</h5>
                <h5 class="card-title"><b>Description : </b>{{ $book->description }}</h5>
                <h5 class="card-title"><b>Status : </b>{{ $book->status }}</h5>
            </div>
        </div>
    </div>
@endsection