routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>['web']],function (){
    Route::get('/', function () {
        return view('welcome')  ;
    });
    Route::resource('home','UserController');
    Route::get('deshboard','UserController@login');
    Route::post('deshboard','UserController@login');
    Route::get('/logout','UserController@logout');
    Route::resource('author','AuthorController');
    Route::post('active/{author}','AuthorController@active');
    Route::resource('book','BookController');
    Route::get('bactive/{book}','BookController@bactive');


});

resources/views/includes/header.blade.php
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{route('home.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('author.index')}}">Author</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('book.index')}}">Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>